### ISSUE TITLE
Broadcast plugin not working with Openfire 4.3

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-broadcast-plugin#2]
Moved from [OF-1716](https://issues.igniterealtime.org/browse/OF-1716)
Forums thread: https://discourse.igniterealtime.org/t/broadcast-plug-in-does-not-work-with-openfire-4-3-2

Broadcast plugin works only with Openfire 4.2 branch. With 4.3 messages are not sent also it is not possible to view readme and changelog in plugins list as it shows empty screen (similar to issues with other plugins).

User also reports this exception:

drwxr-xr-x 3 openfire openfire  4096 Mar 18 13:13 broadcast
-rw-r--r-- 1 openfire openfire  9789 Mar 18 13:13 broadcast.jar

2019.03.18 13:15:54 ERROR [pool-28-thread-1]: org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'broadcast':
java.lang.ClassNotFoundException: org.jivesoftware.openfire.plugin.BroadcastPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:544) [xmppserver-4.3.2.jar:4.3.2]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:354) [xmppserver-4.3.2.jar:4.3.2]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:342) [xmppserver-4.3.2.jar:4.3.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by wrooot** [comment]
Need to try with https://github.com/igniterealtime/openfire-broadcast-plugin/releases/tag/v1.9.1 Maybe it will work now.

**Comment by wrooot** [comment]
Will wait for official 1.9.2 release to test.

**Comment by GregDThomas** [comment]
Fixed in 1.9.2 (now releasing)
